config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tops#top'
  get 'top/about' => 'tops#about'
  get "users/withdrawal" => "users#withdrawal"
  post '/tops/guest_sign_in', to: 'tops#new_guest'
  patch "users/withdrawal" => "users#withdrawal"
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  

  resources :users,only: [:new, :index, :show, :edit, :destroy, :update] do
  resource :relationships, only:[:create, :destroy]
    get 'follower' => 'relationships#follower', as: 'follower'
    get 'followed' => 'relationships#followed', as: 'followed'
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'

  end
   resources :posts do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end


  resources :post, only: [:new, :create, :index, :show, :edit, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
    resource :post_comments, only: [:create, :destroy]
    resource :relationship,only: [:create, :destroy, :followings, :followers]

  end

 post 'follow/:id' => 'relationships#follow', as: 'follow'
 delete 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'search' => 'search#search', as: 'search'

end

app/controllers/search_controller.rb
class SearchController < ApplicationController


def search
    @model = params[:model]
    search = params[:search]
    @keyword = params[:keyword]
    @user = current_user
  if @model == "1"
      @users = User.search(search,@keyword)
  else
      @posts = Post.search(search,@keyword).page(params[:page])
  end

end


end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/_form.html.erb
<div class="row mt-3">
    <div class="col-sm-3">
    </div>
    <div class="col-sm-8 offset-md-1 mx-auto">
      <%= form_with(url: search_path, local: true, method: :get, class: "search-form") do |f| %>
        <%= f.text_field :keyword, class: "search-input" %>
        <%= f.select :model, {'User':"1", 'Post':"2"} %>
        <%= f.select :search, {'Perfect matching':"perfect_match", 'partial_matching':"partial match",'forward matching':"forward_match",'backward matching':"backward_match"} %>

        <%= f.submit "Search", class: "search-btn" %>
      <% end %>
    </div>
  </div>
</div>

app/views/search/search.html.erb
<div class="container">
 <div class="row">
  <div class="col-sm">
<table class='table'>
   <% if @model == '1' %>
    <h3>Users search for "<%= @keyword %>"</h3>
      <%= render 'users/info' %>
      <table class="table table-striped">
  </div>
  </div>

<div class="row">
  <div class="col-sm">
    <% @users.each do |user| %>
    <div class="row border-bottom d-flex align-items-end">
      <div class="col-md-3 col-12"><%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no-image.jpg", class:"mt-3 rounded-circle"; %></div>
      <div class="col-md-3 col-12"><%= user.name %></div>
      <div class="col-md-2 col-12">follows
                                  <%= link_to user_followers_path(user) do %>
                                    <%= user.followers.count %>
                                  <% end %>
      </div>
      <div class="col-md-2 col-12">followers
                                    <%= link_to user_followed_path(user) do %>
                                      <%= user.followings.count %>
                                    <% end %></div>
      <div class="col-md-2 col-12"><% if user != current_user %>
                                     <% if current_user.following?(user) %>
                                       <%= link_to 'フォロー外す', unfollow_path(user.id), method: :delete, class: "btn btn-info" %>
                                     <% else %>
                                        <%= link_to 'フォローする', follow_path(user.id), method: :post, class: "btn btn-success" %>
                                     <% end %>
                                    <% end %>
      </div>
    </div>
    <% end %>
  </div>
  </div>

<% elsif @model == '2' %>
  <h3>Posts search for "<%= @keyword %>"</h3>
    <%= render 'posts/list', posts: @posts %>
      <% end %>
</table>
  <%= render "layouts/footer" %>
</div>