config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tops#top'
  get 'top/about' => 'tops#about'
  get "users/withdrawal" => "users#withdrawal"
  post '/tops/guest_sign_in', to: 'tops#new_guest'
  patch "users/withdrawal" => "users#withdrawal"
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  

  resources :users,only: [:new, :index, :show, :edit, :destroy, :update] do
  resource :relationships, only:[:create, :destroy]
    get 'follower' => 'relationships#follower', as: 'follower'
    get 'followed' => 'relationships#followed', as: 'followed'
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'

  end
   resources :posts do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end


  resources :post, only: [:new, :create, :index, :show, :edit, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
    resource :post_comments, only: [:create, :destroy]
    resource :relationship,only: [:create, :destroy, :followings, :followers]

  end

 post 'follow/:id' => 'relationships#follow', as: 'follow'
 delete 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'search' => 'search#search', as: 'search'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :posts, dependent: :destroy
         has_many :post_comments, dependent: :destroy
         has_many :favorites, dependent: :destroy
         attachment :profile_image
          # 自分がフォローされる（被フォロー）側の関係性
          has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
          # 自分がフォローする（与フォロー）側の関係性
          has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
          # 被フォロー関係を通じて参照→自分をフォローしている人
          has_many :followers, through: :reverse_of_relationships, source: :follower
          # 与フォロー関係を通じて参照→自分がフォローしている人
          has_many :followings, through: :relationships, source: :followed

          def self.guest
            find_or_create_by!(email: 'guest@example.com') do |user|
              user.password = SecureRandom.urlsafe_base64
              # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
            end
          end


          def follow(user_id)
            relationships.create(followed_id: user_id)
          end

          def unfollow(user_id)
            relationships.find_by(followed_id: user_id).destroy
          end

          def following?(user)
            followings.include?(user)
          end

          def User.search(search,keyword)
              if search == "perfect_match"
                @user = User.where("name LIKE?","#{keyword}")
              elsif search == "partial_match"
                @user = User.where("name LIKE(?)","%#{keyword}%")
              elsif search == "forward_match"
                @user = User.where("name LIKE(?)","#{keyword}%")
              elsif search == "backward_match"
                @user = User.where("name LIKE(?)","%#{keyword}")
              else
                @user = User.all
              end
          end


end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).reverse_order
  end

  def edit
    @user = User.find(params[:id])
  end


# おかしい?
  def index
    @users = User.all
    # @user = User.find(current_user.id)
    # @posts = Post.all

  end

  # @usersのイメ-ジ
  @users = [
    {id:1, email: "XXXX", name: "XXXX"},
    {id:2, email: "XXXX", name: "XXXX"},
    {id:3, email: "XXXX", name: "XXXX"},
  ]


  def withdrawal
     @user = current_user
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_info.html.erb
<tr>
    <th>follows</th>
       <th>
          <%= link_to user_followings_path(@user) do %>
            <%= @user.followings.count %>
          <% end %>
      </th>
</tr>
  <tr>
    <th>followers</th>
      <th>
        <%= link_to user_followers_path(@user) do %>
          <%= @user.followers.count %>
        <% end %>
      </th>
  </tr>
    <tr>
      <p><% if @user != current_user %>
          <% if current_user.following?(@user) %>
            <%= link_to 'フォロー外す', unfollow_path(@user.id), method: :delete, class: "btn btn-info" %>
          <% else %>
            <%= link_to 'フォローする', follow_path(@user.id), method: :post, class: "btn btn-success" %>
              <% end %>
                <% end %>
      </p>
    </tr>

app/views/users/_list.html.erb
<div class="card-list-containar py-5">
<div class="row">
    <% @posts.each do |post| %>
      <div class="col-4">
         <div class="card mx-auto mt-4 shadow-lg">
            <%= link_to post_path(post.id) do %>
                <% if post.post_images.present? %>
                  <% post.post_images.first(1).each do |image| %>
                    <%= attachment_image_tag image, :image, class: "card-img-top" %>
                  <% end %>
                <% else %>
                  画像はありません。
                <% end %>
            <% end %>




           </div>
        </div>
      <% end %>
    </div>
 </div>
 
 
 
 
 

app/views/users/edit.html.erb
<div class="newpage">
  <div class="container">
    <div class="row">
      <div class="section-title-wrapper style-1 v1 mx-auto my-5" >
        <h3 class="section-title section-title-sm left">
            <div class="col-md-6 col-md-offset-3 post_image_form-center" >
                <h1>Profile Editing</h1>
        </h3>
<%= form_with model:@user, local:true do |f| %>
    <h4>Profile image</h4>
      <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "no-image.jpg", class:"mt-3 rounded-circle"%>
    <h4>Name</h4>
    <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"name",size:40 %>
    <h4>Introduction</h4>
    <%= f.text_field :introduction, autofocus: true, id:"inputIntroduction", placeholder:"introduction",size:40 %>

      <h4>Photo select</h4>
    <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
    <%= f.submit 'Done' %>
 <% end %>
          </div>
        </div>
     </div>
     <%= render "layouts/footer" %>
  </div>
</div>

app/views/users/show.html.erb
<div class="profile container">
   
    <%= render 'search/form' %>
        <div class="my-5" style="width: 100%; ">
           <div class="row">
               <div class="col-6 text-right">
                   <%= attachment_image_tag @user, :profile_image, :fill, 150, 150,  format: 'jpeg', fallback: "no-image.jpg", class:"mt-3 rounded-circle" %>
              </div>
                <div class="col-6">
                     <h1>
                        <font size="6"><%= @user.name %></h3ships_path(user.id), method: :post, class: "btn btn-success" %></font>
                     </h1>
                         <p>Me：<%= @user.introduction %></p>
                            <%= render 'users/info', users: @users %>
                                <% if @user == current_user %>
                                    <p></h3><%= link_to "Profile Edit", edit_user_path(@user), class: "btn btn-outline-dark" %></p>
                                <% end %>
                </div>
            </div>
        </div>





<div class="card-list-containar container-fluid"style="margin-top:20px;">
    <div class="row">
        <div class="col-md-12">
            <div class="" style="margin-bottom: 15px;">
                <%= render 'users/list', posts: @posts %>
            </div>
         </div>
     </div>
 </div>

<div class="row justify-content-center">
     <%= paginate @posts %>
</div>
    <%= render "layouts/footer" %>
</div>

app/views/users/withdrawal.html.erb
11111111