config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tops#top'
  get 'top/about' => 'tops#about'
  get "users/withdrawal" => "users#withdrawal"
  post '/tops/guest_sign_in', to: 'tops#new_guest'
  patch "users/withdrawal" => "users#withdrawal"
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  

  resources :users,only: [:new, :index, :show, :edit, :destroy, :update] do
  resource :relationships, only:[:create, :destroy]
    get 'follower' => 'relationships#follower', as: 'follower'
    get 'followed' => 'relationships#followed', as: 'followed'
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'

  end
   resources :posts do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end


  resources :post, only: [:new, :create, :index, :show, :edit, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
    resource :post_comments, only: [:create, :destroy]
    resource :relationship,only: [:create, :destroy, :followings, :followers]

  end

 post 'follow/:id' => 'relationships#follow', as: 'follow'
 delete 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'search' => 'search#search', as: 'search'

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  attachment :post_image
  has_many :posts
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_images, dependent: :destroy, autosave: true
  accepts_attachments_for :post_images, attachment: :image

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  validates :text, presence: true
  validates :post_images, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def Post.search(search,keyword)
    if search == "perfect_match"
      @post = Post.where("text LIKE?","#{keyword}")
    elsif search == "partial_match"
      @post = Post.where("text LIKE(?)","%#{keyword}%")
    elsif search == "forward_match"
      @post = Post.where("text LIKE(?)","#{keyword}%")
    elsif search == "backward_match"
      @post = Post.where("text LIKE(?)","%#{keyword}")
    else
      @post = Post.all
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = Post.new
    @post.post_images.build
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    if @post.save
    redirect_to posts_path
    else
      render :new
    end
  end

  def index
    @posts = Post.all
    @posts = Post.page(params[:page]).reverse_order
  end

  def show

    @post = Post.find(params[:id])
    @post_comment = PostComment.new

  end

  def destroy

    @post = Post.find(params[:id])
    @post.destroy



    redirect_to posts_path
  end

  def edit
    @post = Post.find(params[:id])
  end


  def update
    post = Post.find(params[:id])
    post.update(post_params)
    redirect_to  edit_post_path(post)
  end


  private

  def post_params
    params.require(:post).permit(:address, :text, post_images_images: [])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_list.html.erb
<div class="card-list-containar py-5 container">
  <div class="row">
    <div class="col-xs">
      <% @posts.each do |post| %>
        <div class="card w-75 mx-auto mt-5 shadow-lg">
          <%= link_to post_path(post.id) do %>
            <% if post.post_images.present? %>
              <% post.post_images.first(1).each do |image| %>
                <%= attachment_image_tag image, :image, class: "card-img-top" %>
            <% end %>
            <% else %>
            画像はありません。
            <% end %>
      <% end %>

<div class="card-body">
  <div class="row">
    <div class="col-12-lg">
      <%= attachment_image_tag post.user, :profile_image, :fill, 100, 100, fallback: "no-image.jpg", class:"mt-3 rounded-circle"; %>
    </div>
      <div class="col-10">
        <p class="card-title"></p>
          <p class="card-text">TEXT：<%= post.text %></p>
            <span><i class="fas fa-user"></i> By <%= post.user.name %> ｜ </span>

               <span><%= link_to "#{post.post_comments.count} comment", post_path(post.id), class:"text-dark" %></span>
            <span><%= link_to "#{post.favorites.count} favorite", post_path(post.id), class:"text-dark" %></span>



      </div>
  </div>
</div>
        </div>
<% end %>
</div>
</div>

app/views/posts/_map.html.erb
<script type="text/javascript">
function initMap() {

var test ={lat: <%= @post.latitude %>, lng: <%= @post.longitude %>};
var map = new google.maps.Map(document.getElementById('map'), {
zoom: 15,
center: test
});
var transitLayer = new google.maps.TransitLayer();
transitLayer.setMap(map);

var contentString = '住所：<%= @post.address %>';
var infowindow = new google.maps.InfoWindow({
content: contentString
                });


var marker = new google.maps.Marker({
position:test,
map: map,
title: contentString
});

marker.addListener('click', function() {
infowindow.open(map, marker);
});
}
</script>

app/views/posts/_postedit.html.erb
<div class="info">
  <div class="container my-4">
   <div class="row">
     <div class="col">
    <div class="post_pic" >
      <div id="carouselExampleControls" class="carousel slide my-4" data-ride="carousel" data-interval="false">
        <div class="carousel-inner" style="text-align: center">
           <% @post.post_images.first(1).each do |image| %>
             <div class="carousel-item active">
                <%= attachment_image_tag image, :image, :fill, 500, 400, class: "carousel_image" %>
            </div>
           <% end %>
              <% @post.post_images.drop(1).each do |image| %>
                <div class="carousel-item">
                   <%= attachment_image_tag image, :image, :fill, 500, 400, class: "carousel_image" %>
                </div>
              <% end %>
                <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                  <span class="carousel-botton-custom">&lt;</span>
                  <!--<span class="carousel-control-prev-icon" aria-hidden="false"></span>-->
                  <!--<span class="sr-only">Previous</span>-->
                </a>
                  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                    <span class="carousel-botton-custom">&gt;</span>
                      <!--<span class="carousel-control-next-icon" aria-hidden="false"></span>-->
                      <!--<span class="sr-only">Next</span>-->
                  </a>
        </div>
      </div>
    </div>
  </div>
  </div>
  </div>

<div class="col-sm">
  <div class="row border-bottom my-5　d-flex align-items-end">
    <div class="col-md-2 col-12"><%= attachment_image_tag @post.user, :profile_image, :fill, 70, 70, fallback: "no-image.jpg", class:"mt-3 rounded-circle"; %></div>
      <div class="col-md-2 col-12"><%= link_to @post.user.name, user_path(@post.user.id) %></div>
        <div class="col-md-2 col-12"><%= @post.created_at.strftime('%Y/%m/%d') %></div>
          <div class="col-md-2 col-12"><%= @post.text %></div>
            <div class="col-md-1 col-12"><a href="#comments"><%= @post.post_comments.count %></a></div>
              <div class="col-md-1 col-12"><td id="favorite-btn_<%= @post.id %>"><%= render "favorites/favorite" , post: @post %></td></div>
              <% if @post.user == current_user %>
              <div class="col-md-1 col-12"><%= link_to "PostDelete", post_path(@post), class: "fas fa-trash-alt", style: "color: red", method: :delete %></div>
              <% end %>
  </div>
</div>
</div>

app/views/posts/edit.html.erb
<div class="container">
    <h1>EDIT POST</h1>
        <div class="row my-3 mx-auto">
            <div class="col">
          <% if @post.errors.any? %>
             <%= @post.errors.count %>件のエラーが発生しました
             <% @post.errors.full_messages.each do |message| %>
             <%= message %>
            <% end %>
            <% end %>

          <%= form_with model: @post, local: true do |f| %>
            <h4>TEXT</h4>
            <%= f.text_field :text,size:30 %>
            <h4>POST IMAGE</h4>
            <%= f.attachment_field :post_images_images, multiple: true %>
            <%= f.submit '保存' %>
          <% end %>
        </div>
        </div>





<%= render "posts/postedit" %>



<%= render "layouts/footer" %>
</div>

app/views/posts/index.html.erb
<div class="card-list-containar py-5">
  <%= render 'search/form' %>
    <!--render _list.html -->
      <%= render 'posts/list', posts: @posts %>
        <div class="row justify-content-center">
          <%= paginate @posts %>
        </div>
          <%= render "layouts/footer" %>
</div>

app/views/posts/new.html.erb
<div class="newpage">
<div class="container">
    <div class="row">
        <div class="section-title-wrapper style-1 v1 mx-auto my-5" >
        <h3 class="section-title section-title-sm left">
            <div class="col-md-6 col-md-offset-3 post_image_form-center" >
            <h1>POSTFORM</h1>
        </h3>
<% if @post.errors.any? %>
    <%= @post.errors.count %>件のエラーが発生しました
        <% @post.errors.full_messages.each do |message| %>
            <%= message %>
              <% end %>
<% end %>
<%= form_with model: @post, local:true do |f| %>
    <h4>ADDRESS📍</h4>
        <%= f.text_field :address, placeholder: "住所",size:40 %>
          <h4>PHOTO</h4>

              <%= f.attachment_field :post_images_images, multiple: true %>
              <p>You can select multiple images!<p>
                  <h4>TEXT</h4>
                      <%= f.text_area :text %>
                          <%= f.submit 'Post' %>
 <% end %>

              </div>
          </div>
     </div>
     <%= render "layouts/footer" %>
</div>

</div>

app/views/posts/show.html.erb
<div class="container" >
  <div class="post_pic" >




<div id="carouselExampleControls" class="carousel slide my-4" data-ride="carousel" data-interval="false">
  <div class="carousel-inner" style="text-align: center">


     <% @post.post_images.first(1).each do |image| %>
       <div class="carousel-item active">
       <%= attachment_image_tag image, :image, :fill, 500, 400, class: "carousel_image" %>

       </div>
       <% end %>

      <% @post.post_images.drop(1).each do |image| %>
    <div class="carousel-item">
       <%= attachment_image_tag image, :image, :fill, 500, 400, class: "carousel_image" %>

       </div>
       <% end %>




  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-botton-custom">&lt;</span>

  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-botton-custom">&gt;</span>

  </a>

</div>
</div>
</div>
</div>



<div class="container" >

  <div class="mapspeace my-4" style="text-align: center">


            <%= render "posts/map" %>

              <script async defer
                           src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=AIzaSyCfmzjylsHhv2j4fDgS2MypWgSxy3_XX-0&callback=initMap"style="text-align: center">
              </script>

              <style type="text/css">
                #map { height: 300px;
                       width: 100%;
                       text-align: center;
                }
              </style>


              <div id="map"></div>


</div>

</div>




<div class="info">
  <div class="container my-4">
    <div class="row">
      <div class="col-sm">




<span>
      <% if @post.user_id == current_user.id %>
      <%= link_to "", edit_post_path(@post), class: "fas fa-edit", style: "color: green";%>
      <% end %>
</span>

<div class="row border-bottom my-5　d-flex align-items-end">
  <div class="col-md-2 col-12"><%= attachment_image_tag @post.user, :profile_image, :fill, 70, 70, fallback: "no-image.jpg", class:"mt-3 rounded-circle"; %></div>
  <div class="col-md-2 col-12"><i class="fas fa-user"></i><%= link_to @post.user.name, user_path(@post.user.id) %></div>
  <div class="col-md-2 col-12"><i class="fas fa-clock"></i><%= @post.created_at.strftime('%Y/%m/%d') %></div>
  <div class="col-md-2 col-12"><i class="far fa-comment-alt"></i><%= @post.text %></div>
  <div class="col-md-2 col-12"><a href="#comments"><i class="fas fa-comment"></i><%= @post.post_comments.count %></a></div>
  <div class="col-md-2 col-12"><span id="favorite-btn_<%= @post.id %>"><%= render "favorites/favorite" , post: @post %></span></div>
</div>



<h2 class="comment-count my-5"><%= @post.post_comments.count %> comments</h2>
<% @post.post_comments.each do |post_comment| %>
<div class="row border-bottom d-flex align-items-end">
  <div class="col-md-3 col-12"><%= attachment_image_tag post_comment.user, :profile_image, :fill, 50, 50, fallback: "no-image.jpg", class:"mt-3 rounded-circle" %></div>
  <div class="col-md-3 col-12"><i class="fas fa-user"></i><%= link_to post_comment.user.name, user_path(post_comment.user) %></div>
  <div class="col-md-2 col-12"><div class="far fa-comment-alt"><%= post_comment.comment %></div></div>
  <div class="col-md-2 col-12"><span class="fas fa-clock"><%= post_comment.created_at.strftime('%Y/%m/%d') %></div>
  <div class="col-md-2 col-12"><% if post_comment.user == current_user %>
              <%= link_to "", post_post_comment_path(post_comment.post.id, post_comment), method: :delete, class: "fas fa-trash-alt", style: "color: red;" %>
            <% end %></div>
</div>
<% end %>





  <%= form_for [@post, @post_comment] do |f| %>
  <div class="container my-4">
    <div class="row">
<div class="col-sm">
  <h3>Comment</h3>
<%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "comment" %>
   </div>
    </div>
  <%= f.submit "Send", class: "btn btn-lg btn-base-1 mt-20 pu" %>
  <% end %>
  </div>

  </div>
  </div>
  </div>

  <%= render "layouts/footer" %>
  </div>