config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tops#top'
  get 'top/about' => 'tops#about'
  get "users/withdrawal" => "users#withdrawal"
  post '/tops/guest_sign_in', to: 'tops#new_guest'
  patch "users/withdrawal" => "users#withdrawal"
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  

  resources :users,only: [:new, :index, :show, :edit, :destroy, :update] do
  resource :relationships, only:[:create, :destroy]
    get 'follower' => 'relationships#follower', as: 'follower'
    get 'followed' => 'relationships#followed', as: 'followed'
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'

  end
   resources :posts do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end


  resources :post, only: [:new, :create, :index, :show, :edit, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
    resource :post_comments, only: [:create, :destroy]
    resource :relationship,only: [:create, :destroy, :followings, :followers]

  end

 post 'follow/:id' => 'relationships#follow', as: 'follow'
 delete 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'search' => 'search#search', as: 'search'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  attachment :post_image
  has_many :posts
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_images, dependent: :destroy, autosave: true
  accepts_attachments_for :post_images, attachment: :image

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  validates :text, presence: true
  validates :post_images, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def Post.search(search,keyword)
    if search == "perfect_match"
      @post = Post.where("text LIKE?","#{keyword}")
    elsif search == "partial_match"
      @post = Post.where("text LIKE(?)","%#{keyword}%")
    elsif search == "forward_match"
      @post = Post.where("text LIKE(?)","#{keyword}%")
    elsif search == "backward_match"
      @post = Post.where("text LIKE(?)","%#{keyword}")
    else
      @post = Post.all
    end
  end

end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :comment, presence: true
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  belongs_to :post
  attachment :image
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :posts, dependent: :destroy
         has_many :post_comments, dependent: :destroy
         has_many :favorites, dependent: :destroy
         attachment :profile_image
          # 自分がフォローされる（被フォロー）側の関係性
          has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
          # 自分がフォローする（与フォロー）側の関係性
          has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
          # 被フォロー関係を通じて参照→自分をフォローしている人
          has_many :followers, through: :reverse_of_relationships, source: :follower
          # 与フォロー関係を通じて参照→自分がフォローしている人
          has_many :followings, through: :relationships, source: :followed

          def self.guest
            find_or_create_by!(email: 'guest@example.com') do |user|
              user.password = SecureRandom.urlsafe_base64
              # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
            end
          end


          def follow(user_id)
            relationships.create(followed_id: user_id)
          end

          def unfollow(user_id)
            relationships.find_by(followed_id: user_id).destroy
          end

          def following?(user)
            followings.include?(user)
          end

          def User.search(search,keyword)
              if search == "perfect_match"
                @user = User.where("name LIKE?","#{keyword}")
              elsif search == "partial_match"
                @user = User.where("name LIKE(?)","%#{keyword}%")
              elsif search == "forward_match"
                @user = User.where("name LIKE(?)","#{keyword}%")
              elsif search == "backward_match"
                @user = User.where("name LIKE(?)","%#{keyword}")
              else
                @user = User.all
              end
          end


end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController


  def create
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.new(post_id: @post.id)
    favorite.user_id = current_user.id
    favorite.save

  end

  def destroy
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.find_by(post_id: @post.id)
    favorite.destroy


  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = Post.new
    @post.post_images.build
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    if @post.save
    redirect_to posts_path
    else
      render :new
    end
  end

  def index
    @posts = Post.all
    @posts = Post.page(params[:page]).reverse_order
  end

  def show

    @post = Post.find(params[:id])
    @post_comment = PostComment.new

  end

  def destroy

    @post = Post.find(params[:id])
    @post.destroy



    redirect_to posts_path
  end

  def edit
    @post = Post.find(params[:id])
  end


  def update
    post = Post.find(params[:id])
    post.update(post_params)
    redirect_to  edit_post_path(post)
  end


  private

  def post_params
    params.require(:post).permit(:address, :text, post_images_images: [])
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController


def search
    @model = params[:model]
    search = params[:search]
    @keyword = params[:keyword]
    @user = current_user
  if @model == "1"
      @users = User.search(search,@keyword)
  else
      @posts = Post.search(search,@keyword).page(params[:page])
  end

end


end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  skip_before_action :authenticate_user!
  def tops
  end

  def about
  end
  
  def new_guest
    user = User.find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
    end
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).reverse_order
  end

  def edit
    @user = User.find(params[:id])
  end


# おかしい?
  def index
    @users = User.all
    # @user = User.find(current_user.id)
    # @posts = Post.all

  end

  # @usersのイメ-ジ
  @users = [
    {id:1, email: "XXXX", name: "XXXX"},
    {id:2, email: "XXXX", name: "XXXX"},
    {id:3, email: "XXXX", name: "XXXX"},
  ]


  def withdrawal
     @user = current_user
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationship_helper.rb
module RelationshipHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="container" style="margin-top: 200px;">
        <div class="row justify-content-center">

               CopyRight Infratop.inc

    </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <title>N E W V E R Y</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>



  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon">
            </button>

    <div class="container"style="color: gray;">
      <a>N E W V E R Y</a>
      <div class="collapse navbar-collapse" id="navbarSupportedContent" >
        <ul class="navbar-nav ml-auto">

      <% if user_signed_in? %>




              <%= link_to posts_path do %>
                <span class="fas fa-images nav-link text-dark" aria-hidden="true">POST</span>

              <% end %>
            </li>

            <li>
              <%= link_to new_post_path do%>
                <span class="fas fa-camera-retro nav-link text-dark" aria-hidden="true">NEW</span>
              <% end %>
            </li>

            <li>
              <%= link_to user_path(current_user.id) do %>
                <span class="fas fa-user nav-link text-dark" aria-hidden="true">MYPAGE</span>
              <% end %>
            </li>


            <li>
              <%= link_to destroy_user_session_path, method: :delete do%>
                <span class="fas fa-sign-out-alt nav-link text-dark" aria-hidden="true">LOGOUT</span>
              <% end %>
              </li>



          <% else %>

            <li>
              <%= link_to top_about_path do%>
                <span class="fas fa-link nav-link text-dark" aria-hidden="true">About</span>

              <% end %>
            </li>
            <li>
              <%= link_to new_user_registration_path do%>
                <span class="fas fa-user-plus nav-link text-dark" aria-hidden="true">Sing up</span>

              <% end %>
            </li>
            <li>
              <%= link_to new_user_session_path do%><span class="fas fa-sign-in-alt nav-link text-dark" aria-hidden="true">Log in</span>

            <% end %>
            </li>



          <% end %>

          </ul>
      </div>
    </div>
  </nav>
  </header>

  <body>
   <% if flash[:notice] %>
      <p class="success"><%= flash[:notice] %></p>
    <% end %>



    <%= yield %>
    </body>


</html>